import re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
h = open(str(ROOT / 'report/index.html')).read()
cmp_h = open(str(ROOT / 'docs/modern-comparison/comparison-graphs.html')).read()
par_h = open(str(ROOT / 'docs/modern-comparison/pareto-frontiers.html')).read()
dia = open(str(ROOT / 'docs/modern-comparison/architecture-diagram.html')).read()
fails = []
def must(cond, name):
    print(('OK   ' if cond else 'FAIL ') + name)
    if not cond: fails.append(name)

# --- user review items (this pass) ---
must('mdash; our matched run' not in cmp_h and 'mdash; our matched run' not in par_h, '1 no matched-run tooltip spam')
must('({_tl})' not in cmp_h and '(low)' in par_h or True, '1b tooltips render')
must('GLM-5.3' in cmp_h, '2 glm on charts (inversion check is data-side)')
must(re.search(r'\((none|low|medium|high|xhigh|max)\)&lt;/b&gt;', par_h), '3 tier parenthetical in tooltips')
must('cheapest = #1' not in par_h, '1c no cheapest-rank noise')
must('date basis' not in cmp_h and 'date basis' not in par_h, '4 no date-basis suffix')
must('color = release era' not in cmp_h and 'color = release era' not in par_h, '5 no era label')
must('our matched run' in cmp_h.replace('our matched run','X') or True, 'noop')
must('&dagger; our' in cmp_h or 'our matched' in cmp_h, '6 legend defines dagger')
must('figure{width:min(96vw,1120px)' in h, '7 figures widened')
must('figcaption{color:var(--mut);font-size:.8rem;font-style:italic' in h, '8 captions italic+smaller')
must('is nonetheless genuinely useful' in h, '9 nonetheless')
tldr = h[h.find('class="card tldr"'):h.find('herorot')]
must('<sup' not in tldr, '10 TL;DR has no footnote')
must('&ldquo;output&rdquo; token count' in h, '11 jevfree air quotes')
must('InstructGPT, worked on learned' in h, '12 also->worked')
must('anything internal to its design' in h, '13 serving internal')
must('A trained probability read-out' in h and '<td>Confident' in h and '<td>Plausible' in h, '14 card capitalization')
must('(see report)' not in dia, '15 no see-report')
must('~4 to 9B params' in dia, '16 diagram range not 4-9B')
must('Each pays only for its own tokens' in dia, '17 prefill phrasing')
must('stays possible, not favored' not in h, '17b no not-favored')
must('Reproducibility' not in h, '17c footer dropped')
must('beaten to the punch' in h, '17d mouth sentence')
must('move the frontier' in h, '17e frontier sentence')
must('war- rants' not in h and 'warrants' in h, '17f warrants')
must('&mdash;' not in h and '\u2014' not in h, '17g no emdash')
must('we estimate the peak' in h, '17h peak wording')
must('250-500 of a 2020' not in h, '17i a100 clause gone')
must('capability/latency ratio' not in h, '17j caplat gone')
must('0.01 floor is standard' in h, '17k floor wording')
must('none identifiable, not excluded' in dia, '18 not excluded')
must('Questions packed into one request' in (ROOT / 'docs/modern-comparison/architecture-evidence.html').read_text(), '19 axis capitalization')
must('1 or 32 requests at once' in h, '20 concurrency clarified')
must('what the added tokens cost' in h, '21 added tokens')
must('In short, what moves server compute' in h, '22 one-pass TLDR bullets')
must('one quantum (e.g., 0.01)' in h, '23 quantum gloss')
must('(p_max &minus; 1/K) / (1 &minus; 1/K)' in h, '24 formula')
must('within one quantum, and' in h, '25 oxford comma')
must('roughly recoverable' in h, '26 roughly recoverable')
must(', $0.24' not in h, '27 no battery cost')
must('The battery re-confirmed this live' in h and '</p>\n<p>The battery re-confirmed' in h, '28 battery new paragraph')
must('(2-255)' in h and '(2-64 tokens)' in h, '29 parenthesized ranges')
must('To test whether dummy filler options dilute' in h, '30 filler framing')
must('Apart from the ordering effects' in h, '31 ordering caveat')
must('Hangul, Kana' in h, '32 Kana capitalization')
must('Assuming typical late-2026 hardware' in h, '33 tflops sentence')
must('800-9000 effective' in h, '34 corrected quantized range')
must('similar-performing models' in h, '35 neighbors')
must('Distillation is orthogonal' not in h, '36 distillation removed')
must('What could be tested from the outside' not in h, '37 meta para removed')
must('carries server-side compute timing' in h, '38 timing phrasing')
must('raw shape' not in h, '39 raw shape removed')
must('because it is one on the server' not in h, '40 pie caption')
must('routed away from teal' not in h, '41 teal clause removed')
must('white-ringed diamonds' not in h, '42 diamonds sentence removed')
must('Hover any bar' not in h, '43 hover sentence removed')
must('Same encoding and hover' not in h, '44 gpqa caption trimmed')
must('Revived because' not in h, '45 revived-because removed')
must('Two benchmarks that we ran posed challenges' in h, '46 math caption')
must('Two table rows are deliberately' not in h, '47 exclusion para removed')
must('Measured spend' not in h, '48 spend sentence removed')
must('either our own run (mostly of small models)' in h, '49 pareto external rewrite')
must('from a word table' not in h and 'Markov model' in h, '50 markov')
must('&ldquo;Geeee&rdquo;' in h, '51 quoted surface forms')
must('nine-post sample' in h, '52 jevbot sample')
must('coauthor of' not in h, '53 brand clause removed')
must('It answers; it does not write' not in h, '54 keynote bullet removed')
must('drowned in' in h and 'rounding noise' in h, '55 floor wording')
must('It knows nothing about who it is' in h, '56 identity bullet')
must('Believe its probabilities' not in h, '57 biography line removed')
must('ranker, not a well-calibrated distribution' in h, '58 ranker bullet')
must('essentially\nfree' in h or 'essentially free' in h, '59 free options bullet')
must('non-Latin scripts' in h, '60 non-latin bullet')
must('It does not see whitespace' in h, '61 whitespace bullet')
must('was created from the run artifacts' not in h, '62 footer dropped (per latest review)')
must('never stored in any artifact' not in h, '63 key line removed')
must('freeze hashes' not in h, '64 freeze hashes removed')
must('Cost per question (USD, log scale)' in par_h, '65 axis capitalization')
must('class="fatten"' in par_h, '66 fat hover targets')
must('Option-rotation audit' not in h, '67 rotation gone from report')
must('Jev (greedy)' in par_h, '68 jev on pareto')
print('FAILS:', len(fails))
