"""Offline audit reconstruction tests (LEAD-GATE requirement A).

The saved-regression constants below come from the earlier offline audit of
the paired BoolQ run; they are NOT generated by the code under test.
"""

from __future__ import annotations

import json
import math

import pytest

from jev_observatory.audit_offline import (
    REGRESSION_PAIRED_BOOLQ,
    assert_strict_json,
    build_audit_bundle,
    dump_strict_json,
    finite_or_marker,
    reconstruct_mechanism_v3,
    reconstruct_paired_boolq,
)

ROOT = None  # set in fixtures below


PAIRED_RUN = "runs_live/2026-09-18-e1a2252d3ec8"   # BoolQ paired validation
MECH_RUN = "runs_live/2026-09-18-a5200d84836c"     # mechanism v3


@pytest.fixture(scope="module")
def repo_root():
    """Repo root; saved-run regression tests skip in checkouts that omit the
    gated per-item run artifacts (e.g. the published bundle)."""
    from pathlib import Path

    root = Path(__file__).resolve().parent.parent
    if not (root / PAIRED_RUN).is_dir() or not (root / MECH_RUN).is_dir():
        pytest.skip("saved BoolQ/mechanism run artifacts not present",
                    allow_module_level=False)
    return root


# --------------------------------------------------------- paired BoolQ
def test_paired_boolq_reproduction_constants(repo_root):
    """Saved-artifact regression: exact accuracies and Brier scores rebuild."""
    report = reconstruct_paired_boolq(repo_root / PAIRED_RUN)
    choice = report["per_condition"]["boolq_choice"]
    noul = report["per_condition"]["boolq_noul"]
    assert choice["n_correct"] == REGRESSION_PAIRED_BOOLQ["choice_correct"]
    assert noul["n_correct"] == REGRESSION_PAIRED_BOOLQ["noul_correct"]
    assert choice["n_valid"] == REGRESSION_PAIRED_BOOLQ["n_pairs"]
    assert round(choice["binary_brier_p_yes"], 7) == REGRESSION_PAIRED_BOOLQ["choice_brier"]
    assert round(noul["binary_brier_p_yes"], 7) == REGRESSION_PAIRED_BOOLQ["noul_brier"]
    assert report["n_paired_base_records"] == 500


def test_paired_boolq_provenance_and_counts(repo_root):
    report = reconstruct_paired_boolq(repo_root / PAIRED_RUN)
    assert set(report["input_hashes"]) >= {"manifest.json", "items.jsonl", "results.jsonl"}
    assert all(len(h) == 64 for h in report["input_hashes"].values())
    assert report["claim_type"] == "exploratory"
    assert report["n_independent_calls_per_condition"] == {"boolq_choice": 500, "boolq_noul": 500}
    assert "estimator" in report and "bootstrap" in report["estimator"]["brier"]
    assert report["incomplete"] is False


def test_invalid_observations_are_counted_not_dropped(repo_root, tmp_path):
    """A failed record must surface as n_invalid, never silently vanish."""
    import shutil

    work = tmp_path / "run"
    shutil.copytree(repo_root / PAIRED_RUN, work)
    rows = (work / "results.jsonl").read_text().splitlines()
    row = json.loads(rows[0])
    row["status"] = "error"
    rows[0] = json.dumps(row)
    (work / "results.jsonl").write_text("\n".join(rows) + "\n")
    report = reconstruct_paired_boolq(work)
    condition = row["condition"].split(";")[0]
    assert report["per_condition"][condition]["n_invalid_or_missing_rows"] == 1
    assert report["incomplete"] is True


# --------------------------------------------------------- mechanism v3
def test_mechanism_v3_uses_six_pairs_not_distances(repo_root):
    """Sample units are the six repeat pairs; pairwise-distance n is refused."""
    report = reconstruct_mechanism_v3(repo_root / MECH_RUN)
    assert report["n_repeats"] == 6
    assert report["claim_type"] == "exploratory"
    assert "confound" in report["design_caveat"]
    for anchor, block in report["anchors"].items():
        assert set(block["arms"]) == {"alone", "sib8", "renamed8", "reorder8"}
        for arm, arm_block in block["arms"].items():
            assert arm_block["n_valid"] == 6, (anchor, arm)
        for arm, shift in block["paired_shifts_vs_reference"].items():
            assert shift["n_pairs"] == 6
            assert 0.0 <= shift["sign_flip_exact_p_two_sided"] <= 1.0


def test_mechanism_v3_paired_shifts_match_manual_anchor_means(repo_root):
    """dup-charge renamed8 shift equals mean(treatment) - mean(alone) over pairs."""
    report = reconstruct_mechanism_v3(repo_root / MECH_RUN)
    block = report["anchors"]["dup-charge"]
    alone = block["arms"]["alone"]["p_yes_by_repeat"]
    renamed = block["arms"]["renamed8"]["p_yes_by_repeat"]
    expected = statistics_mean([t - a for t, a in zip(renamed, alone)])
    got = block["paired_shifts_vs_reference"]["renamed8"]["mean_signed_shift"]
    assert abs(got - expected) < 1e-12


def statistics_mean(values):
    return sum(values) / len(values)


# --------------------------------------------------------- strict JSON
def test_strict_json_refuses_nonfinite(tmp_path):
    with pytest.raises(ValueError):
        assert_strict_json({"loss": float("inf")})
    with pytest.raises(ValueError):
        assert_strict_json({"a": [float("nan")]})
    # serialisation path represents nonfinite explicitly, never as literals
    dump_strict_json({"loss": {"nonfinite": "inf"}}, tmp_path / "x.json")
    assert "Infinity" not in (tmp_path / "x.json").read_text()


def test_nonfinite_represented_explicitly():
    assert finite_or_marker(float("inf")) == {"nonfinite": "inf"}
    assert finite_or_marker(float("-inf")) == {"nonfinite": "-inf"}
    assert finite_or_marker(float("nan")) == {"nonfinite": "nan"}
    dumped = json.dumps(finite_or_marker({"x": float("inf")}), allow_nan=False)
    assert "Infinity" not in dumped and json.loads(dumped)["x"] == {"nonfinite": "inf"}


def test_bundle_written_strict(repo_root, tmp_path):
    outputs = build_audit_bundle(
        paired_run_dir=repo_root / PAIRED_RUN,
        mech_run_dir=repo_root / MECH_RUN,
        out_dir=tmp_path / "audit",
    )
    assert len(outputs) == 3
    for path in outputs:
        text = path.read_text()
        assert "Infinity" not in text and "NaN" not in text
        json.loads(text)  # strict parse


# ------------------------------------------------------- fail-closed faults (REVIEW-1 #6)
def _copy_run(repo_root, source, tmp_path):
    import shutil

    work = tmp_path / "run"
    shutil.copytree(repo_root / source, work)
    return work


def _rewrite_results(work, rows):
    (work / "results.jsonl").write_text("\n".join(json.dumps(r) for r in rows) + "\n")


def test_duplicate_per_condition_observation_is_refused(repo_root, tmp_path):
    work = _copy_run(repo_root, PAIRED_RUN, tmp_path)
    rows = [json.loads(l) for l in (work / "results.jsonl").read_text().splitlines() if l.strip()]
    choice_row = next(r for r in rows if r["predictions"]["answer"]["type"] == "choice")
    duplicate = json.loads(json.dumps(choice_row))
    duplicate["predictions"]["answer"]["probabilities"]["yes"] = 0.99  # a DIFFERENT observation
    rows.append(duplicate)
    _rewrite_results(work, rows)
    with pytest.raises(ValueError, match="duplicate observation"):
        reconstruct_paired_boolq(work)


def test_missing_yes_probability_is_invalid_not_defaulted(repo_root, tmp_path):
    work = _copy_run(repo_root, PAIRED_RUN, tmp_path)
    rows = [json.loads(l) for l in (work / "results.jsonl").read_text().splitlines() if l.strip()]
    row = next(r for r in rows if r["predictions"]["answer"]["type"] == "choice")
    row["predictions"]["answer"].pop("probabilities")
    _rewrite_results(work, rows)
    report = reconstruct_paired_boolq(work)
    condition = row["condition"].split(";")[0]
    assert report["per_condition"][condition]["n_invalid_or_missing_rows"] == 1
    assert report["incomplete"] is True
    # the constants must NOT be recomputed with a silent 0.0 substitute
    assert report["per_condition"][condition]["n_valid"] == 499


def test_out_of_range_and_nonfinite_probabilities_are_invalid(repo_root, tmp_path):
    work = _copy_run(repo_root, PAIRED_RUN, tmp_path)
    lines = (work / "results.jsonl").read_text().splitlines()
    records = [json.loads(l) for l in lines]
    choice_row = next(r for r in records if r["predictions"]["answer"]["type"] == "choice")
    noul_row = next(r for r in records if r["predictions"]["answer"]["type"] == "noul")
    choice_row["predictions"]["answer"]["probabilities"]["yes"] = 1.5  # out of range
    noul_row["predictions"]["answer"]["noul"] = float("inf")
    _rewrite_results(work, records)  # inf emits a bare Infinity literal on purpose
    report = reconstruct_paired_boolq(work)
    total_invalid = sum(
        c["n_invalid_or_missing_rows"] for c in report["per_condition"].values()
    )
    assert total_invalid >= 2
    assert report["incomplete"] is True


def test_noul_missing_p_yes_is_invalid_not_0_5(repo_root, tmp_path):
    work = _copy_run(repo_root, PAIRED_RUN, tmp_path)
    rows = [json.loads(l) for l in (work / "results.jsonl").read_text().splitlines() if l.strip()]
    noul_row = next(r for r in rows if r["predictions"]["answer"]["type"] == "noul")
    noul_row["predictions"]["answer"].pop("noul")
    _rewrite_results(work, rows)
    report = reconstruct_paired_boolq(work)
    condition = noul_row["condition"].split(";")[0]
    assert report["per_condition"][condition]["n_invalid_or_missing_rows"] == 1


def test_empty_paired_sample_is_unavailable_not_crash(repo_root, tmp_path):
    work = _copy_run(repo_root, PAIRED_RUN, tmp_path)
    rows = [json.loads(l) for l in (work / "results.jsonl").read_text().splitlines() if l.strip()]
    kept = [r for r in rows if str(r["condition"]).split(";")[0] != "boolq_noul"]
    _rewrite_results(work, kept)
    report = reconstruct_paired_boolq(work)
    assert report["result_available"] is False
    assert report["per_condition"] is None and report["paired"] is None
    assert "empty paired sample" in report["unavailable_reason"]
    assert report["incomplete"] is True


def test_planned_missing_results_are_counted(repo_root, tmp_path):
    work = _copy_run(repo_root, PAIRED_RUN, tmp_path)
    rows = [json.loads(l) for l in (work / "results.jsonl").read_text().splitlines() if l.strip()]
    _rewrite_results(work, rows[:-7])  # drop 7 planned results
    report = reconstruct_paired_boolq(work)
    assert sum(report["n_planned_per_condition"].values()) == 1000
    assert sum(report["n_missing_results_per_condition"].values()) == 7
    assert report["incomplete"] is True


def test_mechanism_duplicate_per_block_observation_is_refused(repo_root, tmp_path):
    work = _copy_run(repo_root, MECH_RUN, tmp_path)
    rows = [json.loads(l) for l in (work / "results.jsonl").read_text().splitlines() if l.strip()]
    duplicate = json.loads(json.dumps(rows[1]))
    for qid in list(duplicate["predictions"]):
        if duplicate["predictions"][qid].get("probabilities"):
            duplicate["predictions"][qid]["probabilities"]["yes"] = 0.99
    rows.append(duplicate)
    _rewrite_results(work, rows)
    with pytest.raises(ValueError, match="duplicate observation"):
        reconstruct_mechanism_v3(work)
